version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - phpfpm5
      - phpfpm7
      - django
    volumes:
      - /private/var/lib/docker-volumes/var-www-wordpress:/var/www/wordpress/
      - /private/var/lib/docker-volumes/var-www-woocommerce:/var/www/woocommerce/
      - /private/var/lib/docker-volumes/var-www-drupalcommerce:/var/www/drupalcommerce/
      - /private/var/lib/docker-volumes/var-www-netcat:/var/www/netcat/
      - /private/var/lib/docker-volumes/var-www-amiro:/var/www/amiro/
  mysql:
    build: ./mysql
    restart: always
  phpfpm7:
    build: ./phpfpm7
    restart: always
    depends_on:
      - mysql
    volumes:
      - /private/var/lib/docker-volumes/var-www-wordpress:/var/www/wordpress/
      - /private/var/lib/docker-volumes/var-www-woocommerce:/var/www/woocommerce/
      - /private/var/lib/docker-volumes/var-www-drupalcommerce:/var/www/drupalcommerce/
      - /private/var/lib/docker-volumes/var-www-netcat:/var/www/netcat/
  phpfpm5:
    build: ./phpfpm5
    restart: always
    depends_on:
      - mysql
    volumes:
      - /private/var/lib/docker-volumes/var-www-amiro:/var/www/amiro/
  django:
    build: ./django
    restart: always
    command: /opt/myshop/manage.py runserver 0.0.0.0:8001
    volumes:
      - ./django/myshop/:/opt/myshop
    depends_on:
      - mysql
  wordpress:
    build: ./wordpress
    restart: "no"
    volumes:
      - /private/var/lib/docker-volumes/var-www-wordpress:/var/www/wordpress/
    depends_on:
      - mysql
  woocommerce:
    build: ./woocommerce
    restart: "no"
    volumes:
      - /private/var/lib/docker-volumes/var-www-woocommerce:/var/www/woocommerce/
    depends_on:
      - mysql
  drupalcommerce:
    build: ./drupalcommerce
    restart: "no"
    volumes:
      - /private/var/lib/docker-volumes/var-www-drupalcommerce:/var/www/drupalcommerce/
    depends_on:
      - mysql
  netcat:
    build: ./netcat
    restart: "no"
    volumes:
      - /private/var/lib/docker-volumes/var-www-netcat:/var/www/netcat/
  netcat2:
    build: ./netcat2
    restart: always
    ports:
      - "8055:80"
    volumes:
      - /private/var/lib/docker-volumes/netcat2-var-www-html:/var/www/html
      - /private/var/lib/docker-volumes/netcat2-var-log-httpd:/var/log/httpd
  amiro:
    build: ./amiro
    restart: "no"
    volumes:
      - /private/var/lib/docker-volumes/var-www-amiro:/var/www/amiro/
    depends_on:
      - mysql
