version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - phpfpm5
      - phpfpm7
      - django
    volumes:
      - /private/var/lib/docker-volumes/var-www-wordpress:/var/www/wordpress/
      - /private/var/lib/docker-volumes/var-www-woocommerce:/var/www/woocommerce/
  mysql:
    build: ./mysql
    restart: always
  phpfpm7:
    build: ./phpfpm5
    restart: always
    depends_on:
      - mysql
    volumes:
      - /private/var/lib/docker-volumes/var-www-wordpress:/var/www/wordpress/
      - /private/var/lib/docker-volumes/var-www-woocommerce:/var/www/woocommerce/
  phpfpm5:
    build: ./phpfpm5
    restart: always
    depends_on:
      - mysql
  django:
    build: ./django
    restart: always
    command: /opt/myshop/manage.py runserver 0.0.0.0:8001
    volumes:
      - ./django/myshop/:/opt/myshop
    depends_on:
      - mysql
  wordpress:
    build: ./wordpress
    restart: "no"
    volumes:
      - /private/var/lib/docker-volumes/var-www-wordpress:/var/www/wordpress/
    depends_on:
      - mysql
  woocommerce:
    build: ./woocommerce
    restart: "no"
    volumes:
      - /private/var/lib/docker-volumes/var-www-woocommerce:/var/www/woocommerce/
    depends_on:
      - mysql
