version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - phpfpm
      - django
      - wordpress
    volumes:
      - /private/var/lib/docker-volumes/var-www-wordpress:/var/www/wordpress/
  mysql:
    build: ./mysql
    restart: always
  phpfpm:
    build: ./phpfpm
    restart: always
    depends_on:
      - mysql
    volumes:
      - /private/var/lib/docker-volumes/var-www-wordpress:/var/www/wordpress/
  django:
    build: ./django
    restart: always
    command: /opt/myshop/manage.py runserver 0.0.0.0:8001
    volumes:
      - ./django/myshop/:/opt/myshop
    depends_on:
      - mysql
  wordpress:
    build: ./wordpress
    restart: "no"
    volumes:
      - /private/var/lib/docker-volumes/var-www-wordpress:/var/www/wordpress/
